// /get
export const GET_TODO_REQUEST = "GET_TODO_REQUEST"
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS"
export const GET_TODO_ERROR = "GET_TODO_ERROR"



// post

export const POST_TODO_REQUEST = "POST_TODO_REQUEST"
export const POST_TODO_SUCCESS = "POST_TODO_SUCCESS"
export const POST_TODO_ERROR = "POST_TODO_ERROR"